export const skillIconMapping: IObject = {
    符石轉水: ["conversion", "water_rune"],
    符石轉火: ["conversion", "fire_rune"],
    符石轉木: ["conversion", "earth_rune"],
    符石轉光: ["conversion", "light_rune"],
    符石轉暗: ["conversion", "dark_rune"],
    符石轉心: ["conversion", "heart_rune"],
    五屬版面: ["five_attribute"],
    五屬心版面: ["five_attribute"],
    符石轉水強化: ["conversion", "water_enchanted_rune"],
    符石轉火強化: ["conversion", "fire_enchanted_rune"],
    符石轉木強化: ["conversion", "earth_enchanted_rune"],
    符石轉光強化: ["conversion", "light_enchanted_rune"],
    符石轉暗強化: ["conversion", "dark_enchanted_rune"],
    符石轉心強化: ["conversion", "heart_enchanted_rune"],
    水轉其他: ["conversion"],
    火轉其他: ["conversion"],
    木轉其他: ["conversion"],
    光轉其他: ["conversion"],
    暗轉其他: ["conversion"],
    心轉其他: ["conversion"],
    指定符石轉其他: ["conversion"],
    符石兼具水: ["possession"],
    符石兼具火: ["possession"],
    符石兼具木: ["possession"],
    符石兼具光: ["possession"],
    符石兼具暗: ["possession"],
    符石兼具心: ["possession"],
    符石效果提升: ["possession"],
    強化珠效果提升: ["enchanted_rune"],
    水屬追打: ["extra_attack", "water"],
    火屬追打: ["extra_attack", "fire"],
    木屬追打: ["extra_attack", "earth"],
    光屬追打: ["extra_attack", "light"],
    暗屬追打: ["extra_attack", "dark"],
    無屬追打: ["extra_attack"],
    五屬追打: ["all_attribute_hit_shield"],
    自身追打: ["extra_attack"],
    全隊追打: ["extra_attack"],
    引爆: ["explode"],
    整版引爆: ["explode"],
    直行引爆: ["explode"],
    橫行引爆: ["explode"],
    X型引爆: ["explode"],
    多次引爆: ["explode"],
    水符石引爆: ["explode_water"],
    火符石引爆: ["explode_fire"],
    木符石引爆: ["explode_earth"],
    光符石引爆: ["explode_light"],
    暗符石引爆: ["explode_dark"],
    心符石引爆: ["explode_heart"],
    水外符石引爆: ["explode"],
    火外符石引爆: ["explode"],
    木外符石引爆: ["explode"],
    光外符石引爆: ["explode"],
    暗外符石引爆: ["explode"],
    心外符石引爆: ["explode"],
    指定符石引爆: ["explode"],
    指定符石外引爆: ["explode"],
    移除: ["remove"],
    整版移除: ["remove"],
    直行移除: ["remove"],
    橫行移除: ["remove"],
    水符石移除: ["explode_water"],
    火符石移除: ["explode_fire"],
    木符石移除: ["explode_earth"],
    光符石移除: ["explode_light"],
    暗符石移除: ["explode_dark"],
    心符石移除: ["explode_heart"],
    指定符石移除: ["remove"],
    指定符石外移除: ["remove"],
    人族符石製造: ["human_rune"],
    獸族符石製造: ["beast_rune"],
    妖族符石製造: ["elf_rune"],
    龍族符石製造: ["dragon_rune"],
    神族符石製造: ["god_rune"],
    魔族符石製造: ["demon_rune"],
    機械族符石製造: ["mechina_rune"],
    符石強化: ["enchanted_rune"],
    大幅轉版: ["conversion"],
    固定版面: ["all_attribute_hit_shield"],
    還原版面: ["restore"],
    禁珠: ["undissolvable"],
    改變掉落機率: ["drop"],
    天降強制掉落: ["drop"],
    引爆強制掉落: ["drop", "explode"],
    移除強制掉落: ["drop", "remove"],
    增加符石: ["add_rune"],
    記錄版面: ["five_attribute"],
    加護符石製造: ["protected_rune"],
    音樂符石製造: ["music_rune"],
    淡化印記製造: ["yang_energy", "dilution_mark"],
    淨化印記製造: ["yin_energy", "purification_mark"],
    強制掉水: ["drop", "water_rune"],
    強制掉火: ["drop", "fire_rune"],
    強制掉木: ["drop", "earth_rune"],
    強制掉光: ["drop", "light_rune"],
    強制掉暗: ["drop", "dark_rune"],
    強制掉心: ["drop", "heart_rune"],
    強制掉直行屬性: ["drop"],
    一消: ["change_dissolve", "number_1"],
    二消: ["change_dissolve", "number_2"],
    三消: ["change_dissolve", "number_3"],
    只能首消符石: ["no_drop"],
    減傷: ["reduce_damage"],
    硬減傷: ["reduce_damage"],
    意志: ["determination"],
    敵方減攻: ["atk_deduction"],
    迴避: ["stealth"],
    回血: ["recover"],
    我方傷害吸收: ["absorb"],
    敵方傷害吸收: ["absorb"],
    破防: ["break_def"],
    屬性剋制改變: ["change_attribute"],
    溢補攻擊: ["overheal"],
    排珠: ["move_rune"],
    延長轉珠時間: ["time_extension"],
    反擊: ["reflect"],
    再爆發: ["break_out"],
    軌跡轉化: ["trail_conversion"],
    直傷: ["direct_damage"],
    回合初直傷: ["direct_damage", "first_strike"],
    破防直傷: ["direct_damage", "break_def"],
    破強化直傷: ["direct_damage", "enchanted_shield"],
    無視技能直傷: ["direct_damage", "no_skill"],
    消耗: ["direct_damage"],
    增傷: ["atk_up"],
    界王拳: ["atk_up", "super_damage"],
    敵方受傷增加: ["atk_up"],
    攻擊轉屬: ["change_attribute"],
    繼承傷害: ["inherit"],
    增回: ["rec_up"],
    我方攻擊力吸收: ["trojan"],
    共鳴: ["resonance"],
    Combo時增攻: ["atk_up"],
    Combo時增回: ["rec_up"],
    對人類增傷: ["atk_up", "human_atk"],
    對獸類增傷: ["atk_up", "beast_atk"],
    對妖精類增傷: ["atk_up", "elf_atk"],
    對龍類增傷: ["atk_up", "dragon_atk"],
    對神族增傷: ["atk_up", "god_atk"],
    對魔族增傷: ["atk_up", "demon_atk"],
    對機械族增傷: ["atk_up", "mechina_atk"],
    增加Combo: ["add_combo"],
    "增加Ex.Combo": ["add_ex_combo"],
    固定Combo: ["fixed_combo"],
    "固定Ex.Combo": ["fixed_combo"],
    延遲: ["delay"],
    減CD: ["cd_recovery"],
    回復EP: ["cd_recovery"],
    EP消耗減少: ["ep_cost_deduction"],
    附加消除: ["neutralize"],
    龍脈儀蓄能: ["craft_recovery"],
    時晷蓄能: ["fp"],
    行動值提升: ["mechina_mark"],
    刷新護盾: ["shield_recover"],
    還原龍脈儀: ["craft_crash"],
    隨時關閉: ["reset_cd"],
    變身: ["evolve"],
    合體: ["combine"],
    吞併: ["combine"],
    多重左上狀態: ["multi_effect"],
    頭像狀態: ["badge"],
    敵身狀態: ["uncontrollable"],
    亢奮狀態: ["energetic"],
    疲憊狀態: ["fatigue"],
    暴擊狀態: ["energetic"],
    暴怒狀態: ["energetic", "angry"],
    無法行動: ["uncontrollable"],
    凍結敵方: ["frozen"],
    點燃敵方: ["burn"],
    石化敵方: ["petrified"],
    電擊敵方: ["electrified"],
    寄生敵方: ["parasite"],
    敵方中毒: ["poisoned"],
    敵附烈毒: ["venomed"],
    敵方自我攻擊: ["stunned"],
    魅惑敵方: ["seduced"],
    暈擊敵方: ["stunned"],
    冥控敵方: ["eclipsed"],
    敵方睡眠: ["sleep"],
    敵附刀傷: ["katana"],
    暴風牽制敵方: ["storm"],
    束縛敵方: ["chain"],
    威壓敵方: ["coercion"],
    敵方轉水: ["water"],
    敵方轉火: ["fire"],
    敵方轉木: ["earth"],
    敵方轉光: ["light"],
    敵方轉暗: ["dark"],
    解鎖: ["shackle"],
    解除疲憊: ["fatigue"],
    解除休眠: ["hypnosis"],
    解除風壓: ["windswept"],
    解除麻痺: ["paralyzed"],
    解除沉默: ["silenced"],
    防鎖: ["shackle"],
    防毒: ["prevent_poison"],
    解除自爆: ["prevent_death_blow"],
    防反饋: ["retaliation"],
    防反擊: ["prevent_reflect"],
    防漆黑: ["black_hole"],
    解除暴風: ["storm"],
    解除射擊: ["laser"],
    解除結界地型: ["enclosed_area"],
    解除隱身: ["stealth"],
    解除殞命輪迴: ["skull"],
    解除終結倒數: ["countdown"],
    解除石牢: ["stone_jail"],
    黑白還原: ["monochrome"],
    碎裂還原: ["crack"],
    無視燃燒: ["burn"],
    無視黏腐: ["sticky"],
    無視暴風: ["storm"],
    無視電擊: ["electrified_rune"],
    無視射擊: ["laser"],
    無視瘴氣: ["smog"],
    無視黑洞: ["black_hole"],
    無視一步一傷: ["step_damage"],
    無視灼熱地型: ["scorching_area"],
    無視火焰地型: ["flaming_area"],
    無視血浴地型: ["blood_area"],
    無視角色符石地型: ["character_rune_area_shield"],
    無視符石禁消: ["undissolvable"],
    無視只能首消符石: ["no_drop"],
    無視邪惡符石: ["evil_haze"],
    無視回復顛倒: ["recovery_inversion"],
    無視腐化: ["corruption"],
    無視敵身減傷: ["damage_deduction"],
    無視減傷抗性: ["damage_reduce_resistance"],
    無視開技扣血: ["cost"],
    無視紅綠燈: ["vortex"],
    無視步數限制: ["step_restriction"],
    無視移形換影: ["shrouded_rune"],
    無視拼圖盾: ["puzzle_shield"],
    無視攻前盾: ["initial_shield"],
    無視強化盾: ["enchanted_shield"],
    無視二屬盾: ["fusion_shield_2"],
    無視三屬盾: ["fusion_shield_3"],
    無視四屬盾: ["fusion_shield_4"],
    無視五屬盾: ["fusion_shield_5"],
    "無視%數盾": ["percent_shield"],
    無視固定連擊盾: ["fixed_combo_shield"],
    無視連擊相等盾: ["same_combo_shield"],
    無視反首消盾: ["anti_first_batch_shield"],
    無視全首消盾: ["all_first_batch_shield"],
    無視首消全版盾: ["all_rune_shield"],
    無視數字盾: ["number_shield"],
    無視十字盾: ["cross_shaped_shield"],
    無視L字盾: ["l_shaped_shield"],
    無視T字盾: ["t_shaped_shield"],
    無視攻擊次數盾: ["hit_shield"],
    無視首消組數屬性盾: ["attributive_rune_shield"],
    無視首消相同種類盾: ["same_type_shield"],
    無視首消不同種類盾: ["different_type_shield"],
    無視累積符石盾: ["accumulate_shield"],
    無視首殺盾: ["first_blood_shield"],
    無視追擊零化: ["combo_trojan"],
    無視連擊法印: ["orb_shield"],
    無視力的印記: ["strength_mark"],
    風化符石處理: ["weathered_rune"],
    凍結符石處理: ["frozen_rune"],
    弱化符石處理: ["weaken_rune"],
    電擊符石處理: ["electrified_rune"],
    石化符石處理: ["petrified_rune"],
    化血符石處理: ["reverse_lock"],
    凝結符石處理: ["condensed_rune"],
    爆破炸彈處理: ["bomb_rune"],
    泡沫符石處理: ["bubble_rune"],
    我方減攻: ["atk_deduction"],
    我方減回: ["rec_deduction"],
    我方扣血: ["self_deplete"],
    限制成員攻擊: ["attack_block"],
    我方受傷增加: ["more_damage"],

    //
    增攻: ["atk_up"],
    增血: ["hp_up"],
    主動技改變: ["change"],
    隊長技改變: ["change"],
    兼具隊長技能: ["change"],
    龍脈儀能力: ["craft"],
    召喚獸轉水: ["water"],
    召喚獸轉火: ["fire"],
    召喚獸轉木: ["earth"],
    召喚獸轉光: ["light"],
    召喚獸轉暗: ["dark"],
    水兼具其他: ["possession"],
    火兼具其他: ["possession"],
    木兼具其他: ["possession"],
    光兼具其他: ["possession"],
    暗兼具其他: ["possession"],
    心兼具其他: ["possession"],
    護盾: ["shield_recover"],
    爆擊: ["super_damage"],
    攻擊力共鳴: ["resonance"],
    回復力共鳴: ["recover"],
    生命力共鳴: ["hp"],
    符石掉落率提升: ["drop"],
    強制掉落: ["drop"],
    進場減CD: ["cd_recovery"],
    永久減CD: ["cd_recovery"],
    開技減CD: ["cd_recovery"],
    其他減CD: ["cd_recovery"],
    進場回EP: ["cd_recovery"],
    開技回EP: ["cd_recovery"],
    其他回EP: ["cd_recovery"],
    防疲憊: ["fatigue"],
    防休眠: ["hypnosis"],
    防風壓: ["windswept"],
    防麻痺: ["paralyzed"],
    防沉默: ["silenced"],
    防拘束: ["chain"],
    防殞命輪迴: ["skull"],
    防爆: ["prevent_death_blow"],
    防觸電: ["electrified"],
    防血量囚錮: ["hp_lock"],
    防碎裂: ["crack"],
    防暴風: ["storm"],
    防射擊: ["laser"],
    防結界地型: ["enclosed_area"],
    防黑白: ["monochrome"],
    龍脈儀抗性: ["craft_crash"],
    混沌值抗性: ["chaos"],
    崩壞值抗性: ["corrupt"],
    鏽化值抗性: ["rust"],
    無視縮時地型: ["time_reduction"],
    無視虛之印記: ["sombre_mark"],
    無視能力點消耗: ["trojan"],
    無視EP消耗代價: ["ep_cost_increase"],
    無視技能重置: ["reset_cd"],
    無視陽之氣: ["yang_energy"],
    無視炎之氣: ["fire_energy"],
    無視雷之氣: ["thunder_energy"],
    解除迷霧: ["mist"],
    物品掉落增加: ["coin"],

    //

    四消: ["change_dissolve", "number_4"],
    三十消: ["change_dissolve", "number_30"],
    回EP: ["cd_recovery"],
    單體轉全體: ["multi_attack"],
    對水增傷: ["atk_up", "water_atk"],
    對火增傷: ["atk_up", "fire_atk"],
    對木增傷: ["atk_up", "earth_atk"],
    對光增傷: ["atk_up", "light_atk"],
    對暗增傷: ["atk_up", "dark_atk"],
    對特定敵方增傷: ["atk_up"],
    減少轉珠時間: ["time_reduction"],
    總血量減少: ["hp_deduction"],

    //

    直行轉水: ["conversion", "water_rune"],
    直行轉火: ["conversion", "fire_rune"],
    直行轉木: ["conversion", "earth_rune"],
    直行轉光: ["conversion", "light_rune"],
    直行轉暗: ["conversion", "dark_rune"],
    直行轉心: ["conversion", "heart_rune"],
    橫行轉水: ["conversion", "water_rune"],
    橫行轉火: ["conversion", "fire_rune"],
    橫行轉木: ["conversion", "earth_rune"],
    橫行轉光: ["conversion", "light_rune"],
    橫行轉暗: ["conversion", "dark_rune"],
    橫行轉心: ["conversion", "heart_rune"],
    全體直傷: ["direct_damage"],
    全體破防直傷: ["direct_damage", "break_def"],
    單體直傷: ["direct_damage"],
    單體破防直傷: ["direct_damage", "break_def"],
    無視屬性相剋: ["change_attribute"],
    自身增傷: ["atk_up", "super_damage"],
    水屬增傷: ["atk_up", "water_atk"],
    火屬增傷: ["atk_up", "fire_atk"],
    木屬增傷: ["atk_up", "earth_atk"],
    光屬增傷: ["atk_up", "light_atk"],
    暗屬增傷: ["atk_up", "dark_atk"],
    人類增傷: ["atk_up", "human_atk"],
    獸類增傷: ["atk_up", "beast_atk"],
    妖精類增傷: ["atk_up", "elf_atk"],
    龍類增傷: ["atk_up", "dragon_atk"],
    神族增傷: ["atk_up", "god_atk"],
    魔族增傷: ["atk_up", "demon_atk"],
    機械族增傷: ["atk_up", "mechina_atk"],
    對人增傷: ["atk_up", "human_atk"],
    對獸增傷: ["atk_up", "beast_atk"],
    對妖精增傷: ["atk_up", "elf_atk"],
    對龍增傷: ["atk_up", "dragon_atk"],
    對神增傷: ["atk_up", "god_atk"],
    對魔增傷: ["atk_up", "demon_atk"],
    對機械增傷: ["atk_up", "mechina_atk"],
    追打: ["extra_attack"],
}
